image: docker:25.0.3

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - main
    changes:
      - "**/*.java"
      - "**/*.xml"
      - "**/*.sql"
      - "src/main/resources/**/*"
      - "pom.xml"
      - "Dockerfile"
      - "docker-compose.yml"

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - 'curl -H "Authorization: Bearer $WATCHTOWER_HTTP_API_TOKEN" http://201.182.97.84:8086/v1/update'
  only:
    refs:
      - main
  when: on_success
